version: '3.8'

services:
  postgres:
    image: postgres
    container_name: skeleton
    restart: always
    ports:
      - "5433:5432"  # Host:Container (External port 5433 → Internal 5432)
    environment:
      POSTGRES_USER: skeleton
      POSTGRES_PASSWORD: skeleton
      POSTGRES_DB: skeleton
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data: